### ISSUE TITLE
Plugin incompatible with Jellyfin 10.9.x

### ISSUE THREAD

**Issue by GeiserX** [jellyfin/jellyfin-plugin-webhook#235] opened 2024-05-15 20:24 UTC
Check forum post: https://forum.jellyfin.org/t-webhooks-no-longer-work-since-update-to-10-9

**Comment by crobibero** [comment] 2024-05-15 20:25
Duplicate of https://github.com/jellyfin/jellyfin-plugin-webhook/issues/232

**Closed by crobibero** 2024-05-15 20:25 UTC

**Comment by GeiserX** [comment] 2024-05-15 20:28
Great! Thank you. But would you create a new Release so that we can have the functionality back?

**Comment by crobibero** [comment] 2024-05-15 20:29
Release isn't ready yet, there is another issue to fix before it is.
