### ISSUE TITLE
Discord ItemAdded broken for Jellyfin 10.9

### ISSUE THREAD

**Issue by haloTT100** [jellyfin/jellyfin-plugin-webhook#237] opened 2024-05-16 14:57 UTC
Server version: 10.9.1
Webhook version: 13.0.0.0

I have updated my Jellyfin server to 10.9.1 from 10.8.13, before the update I was getting notified on Discord, but now I don't.
I'm using the template from Jellyfin.Plugin.Webhook/Templates/Discord/ItemAdded.handlebars and I'm not getting notified on Discord when I add anything.

I attached my full server log from start to shutdown. [log_20240516.log](https://github.com/jellyfin/jellyfin-plugin-webhook/files/15337080/log_20240516.log)

On line 5528 Jellyfin finds the newly added movie. After adding it I didn't get notified on Discord. I waited some time, but nothing, I could see it in my library. I went to my Webhook settings and turned on the playback start notification and started playing the newly added movie.
On line 6693 Webhook successfully sent with the playback start notification, attached screenshot below.
Same thing on line 7107
![Screenshot_9](https://github.com/jellyfin/jellyfin-plugin-webhook/assets/44986488/bc37beab-b4d5-489a-bfb2-ce64cfe82a0a)

**Comment by crobibero** [comment] 2024-05-16 15:10
Duplicate of https://github.com/jellyfin/jellyfin-plugin-webhook/issues/232

**Closed by crobibero** 2024-05-16 15:10 UTC
