### ISSUE TITLE
Discord Item Added Not working

### ISSUE THREAD

**Issue by Sandman1294** [jellyfin/jellyfin-plugin-webhook#236] opened 2024-05-16 03:51 UTC
Discord Item Added not working with Jellyfin 10.9.1

I confirmed the webhook works fine with the Playback starting.
But will not work with the item added.

I am using the template that is included with the plugin.

I am having it log but it gives no errors.

All it give me is that the Webhook Item Added Notifier runs successfully. But it does not pass the message over to the webhook in discord.

Has anyone else had any luck getting this to work?

**Comment by crobibero** [comment] 2024-05-16 08:41
Duplicate of https://github.com/jellyfin/jellyfin-plugin-webhook/issues/232

**Closed by crobibero** 2024-05-16 08:41 UTC
